/**
  * @file       config_lcd.h
  * @brief      User Interface - LCD Configuration
  * @author     Igor T. <research.tahoe@gmail.com>
  */


#ifndef  CONFIG_LCD_H
#define  CONFIG_LCD_H


#define LCD_SPEC_XSIZE                  1024
#define LCD_SPEC_YSIZE                  600

#define LCD_SPEC_HSYNC_PULSE_WIDTH      70
#define LCD_SPEC_HSYNC_BACK_PORCH       160
#define LCD_SPEC_HSYNC_FRONT_PORCH      160
#define LCD_SPEC_HSYNC_ACTIVE_WIDTH     (LCD_SPEC_XSIZE + LCD_SPEC_HSYNC_BACK_PORCH)
#define LCD_SPEC_HSYNC_PERIOD_TOTAL     (LCD_SPEC_XSIZE + LCD_SPEC_HSYNC_BACK_PORCH + LCD_SPEC_HSYNC_FRONT_PORCH)

#define LCD_SPEC_VSYNC_PULSE_WIDTH      10
#define LCD_SPEC_VSYNC_BACK_PORCH       23
#define LCD_SPEC_VSYNC_FRONT_PORCH      12
#define LCD_SPEC_VSYNC_ACTIVE_WIDTH     (LCD_SPEC_YSIZE + LCD_SPEC_VSYNC_BACK_PORCH)
#define LCD_SPEC_VSYNC_PERIOD_TOTAL     (LCD_SPEC_YSIZE + LCD_SPEC_VSYNC_BACK_PORCH + LCD_SPEC_VSYNC_FRONT_PORCH)


#endif	//CONFIG_LCD_H
